Migrate <NavLink />
whiplashmerch/horcrux pull request #35
Opened 2017-05-08 21:52 UTC by azamatsmith

closes #26

2017-05-09 13:19 UTC, caseybaggz requested changes
Just annoying tests updates. :P

2017-05-09 13:19 UTC, caseybaggz commented on src/tests/NavLink.test.js
> +  it('should have a to prop', () => {
Eep! We need to add those `const`

2017-05-15 13:56 UTC, caseybaggz commented
@azamatsmith I'm using react-router already on the demo side, so you can go ahead and remove it again so there is no conflict later. 👍

2017-05-15 19:35 UTC, azamatsmith commented
@caseybaggz we can wait on this one. Right now looks like it will need to have `react-router` as a dependency in it's `package.json` file as it is trying to locate `react-router` from the non-root `node_modules` folder which obviously does not exist there.

2018-05-23 12:35 UTC, closed without merging